language: "node_js"
node_js: "8"

cache:
  directories:
    - "node_modules"

notifications:
  email: false

before_deploy: "npm run pre-build"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  repo: aya-experience/aya-day-game
  target_branch: gh-pages
  on:
    branch: master
